const fs = require('fs')
const path = require('path')

const DB_PATH = '/app/backend/data/moncv.json'

const templates = [
  { id: 'classic-blue', name: 'Classique Bleu', description: 'Sobre et professionnel, idéal pour les secteurs traditionnels.', preview: '/previews/classic-blue.svg', category: 'classique', layout: 'single-column', fonts: { heading: 'Merriweather', body: 'Inter' }, defaultColors: { primary: '#1e3a5f', secondary: '#3b82f6', accent: '#e2e8f0' } },
  { id: 'modern-teal', name: 'Moderne Sarcelle', description: 'Design épuré avec une touche de couleur.', preview: '/previews/modern-teal.svg', category: 'moderne', layout: 'two-column', fonts: { heading: 'Poppins', body: 'Inter' }, defaultColors: { primary: '#0d9488', secondary: '#14b8a6', accent: '#ccfbf1' } },
  { id: 'creative-coral', name: 'Créatif Corail', description: 'Audacieux pour les métiers créatifs.', preview: '/previews/creative-coral.svg', category: 'créatif', layout: 'two-column', fonts: { heading: 'Playfair Display', body: 'Inter' }, defaultColors: { primary: '#e11d48', secondary: '#fb7185', accent: '#ffe4e6' } },
  { id: 'minimal-slate', name: 'Minimaliste Ardoise', description: "Élégant et aéré, l'essentiel sans fioritures.", preview: '/previews/minimal-slate.svg', category: 'minimaliste', layout: 'single-column', fonts: { heading: 'Inter', body: 'Inter' }, defaultColors: { primary: '#334155', secondary: '#64748b', accent: '#f1f5f9' } },
  { id: 'elegant-navy', name: 'Élégant Marine', description: 'Tons sombres pour un CV qui impose.', preview: '/previews/elegant-navy.svg', category: 'classique', layout: 'single-column', fonts: { heading: 'Lora', body: 'Inter' }, defaultColors: { primary: '#1e293b', secondary: '#f8fafc', accent: '#cbd5e1' } },
  { id: 'fresh-green', name: 'Fresh Vert', description: 'Dynamique et naturel.', preview: '/previews/fresh-green.svg', category: 'moderne', layout: 'two-column', fonts: { heading: 'Urbanist', body: 'Inter' }, defaultColors: { primary: '#166534', secondary: '#22c55e', accent: '#dcfce7' } },
  { id: 'bold-purple', name: 'Bold Violet', description: 'Pour les profils ambitieux.', preview: '/previews/bold-purple.svg', category: 'créatif', layout: 'two-column', fonts: { heading: 'Plus Jakarta Sans', body: 'Inter' }, defaultColors: { primary: '#6d28d9', secondary: '#8b5cf6', accent: '#ede9fe' } },
  { id: 'clean-ivory', name: 'Clean Ivoire', description: 'Blanc et noir, simplicité intemporelle.', preview: '/previews/clean-ivory.svg', category: 'minimaliste', layout: 'single-column', fonts: { heading: 'DM Serif Display', body: 'DM Sans' }, defaultColors: { primary: '#1c1917', secondary: '#78716c', accent: '#f5f5f4' } },
  { id: 'professional-indigo', name: 'Professionnel Indigo', description: 'Parfait pour la finance, le conseil et le droit.', preview: '/previews/professional-indigo.svg', category: 'classique', layout: 'single-column', fonts: { heading: 'Source Serif 4', body: 'Source Sans 3' }, defaultColors: { primary: '#312e81', secondary: '#6366f1', accent: '#e0e7ff' } },
  { id: 'vibrant-amber', name: 'Vibrant Ambre', description: 'Accents chauds pour un CV qui rayonne.', preview: '/previews/vibrant-amber.svg', category: 'moderne', layout: 'two-column', fonts: { heading: 'Manrope', body: 'Inter' }, defaultColors: { primary: '#92400e', secondary: '#f59e0b', accent: '#fef3c7' } },
  { id: 'side-bar-sapphire', name: 'Barre Latérale Saphir', description: 'Colonne latérale colorée, CV structuré et moderne.', preview: '/previews/side-bar-sapphire.svg', category: 'moderne', layout: 'two-column', fonts: { heading: 'Raleway', body: 'Open Sans' }, defaultColors: { primary: '#1e3a8a', secondary: '#3b82f6', accent: '#dbeafe' } },
  { id: 'timeless-charcoal', name: 'Intemporel Charcoal', description: 'Gris anthracé pour un CV sérieux et moderne.', preview: '/previews/timeless-charcoal.svg', category: 'minimaliste', layout: 'single-column', fonts: { heading: 'Inter', body: 'Inter' }, defaultColors: { primary: '#1f2937', secondary: '#6b7280', accent: '#f3f4f6' } },
  { id: 'europass-inspired', name: 'Europass Modernisé', description: 'Inspiré du format Europass, modernisé pour 2024.', preview: '/previews/europass-inspired.svg', category: 'classique', layout: 'two-column', fonts: { heading: 'Calibri', body: 'Calibri' }, defaultColors: { primary: '#2c3e50', secondary: '#3498db', accent: '#ecf0f1' } },
  { id: 'ats-friendly', name: 'ATS Friendly', description: 'Optimisé pour les systèmes de suivi des candidatures (ATS).', preview: '/previews/ats-friendly.svg', category: 'minimaliste', layout: 'single-column', fonts: { heading: 'Arial', body: 'Arial' }, defaultColors: { primary: '#2d3436', secondary: '#636e72', accent: '#f5f6fa' } },
  { id: 'creative-artist', name: 'Créatif Artistique', description: 'Un design audacieux pour les profils artistiques et créatifs.', preview: '/previews/creative-artist.svg', category: 'créatif', layout: 'two-column', fonts: { heading: 'Montserrat', body: 'Lato' }, defaultColors: { primary: '#6c5ce7', secondary: '#fd79a8', accent: '#dfe6e9' } },
  { id: 'fonctionnel', name: 'Fonctionnel', description: 'CV axé sur les compétences, parfait pour les reconversions.', preview: '/previews/fonctionnel.svg', category: 'moderne', layout: 'single-column', fonts: { heading: 'Segoe UI', body: 'Segoe UI' }, defaultColors: { primary: '#006266', secondary: '#00b894', accent: '#ffeaa7' } },
  { id: 'scientifique', name: 'Scientifique', description: 'Mise en page claire pour les profils techniques et scientifiques.', preview: '/previews/scientifique.svg', category: 'classique', layout: 'single-column', fonts: { heading: 'Georgia', body: 'Georgia' }, defaultColors: { primary: '#1b1464', secondary: '#0652DD', accent: '#f1f2f6' } },
  { id: 'informatique', name: 'Informatique / IT', description: 'Design moderne pour les développeurs et ingénieurs IT.', preview: '/previews/informatique.svg', category: 'moderne', layout: 'two-column', fonts: { heading: 'Fira Code', body: 'Inter' }, defaultColors: { primary: '#0abde3', secondary: '#10ac84', accent: '#c8d6e5' } },
  { id: 'commercial', name: 'Commercial / Vente', description: 'Template percutant pour les profils commerciaux.', preview: '/previews/commercial.svg', category: 'moderne', layout: 'two-column', fonts: { heading: 'Roboto Condensed', body: 'Roboto' }, defaultColors: { primary: '#e84118', secondary: '#c23616', accent: '#f5f6fa' } },
  { id: 'medical', name: 'Médical / Santé', description: 'Pour les infirmiers, médecins et professionnels de santé.', preview: '/previews/medical.svg', category: 'classique', layout: 'single-column', fonts: { heading: 'Lato', body: 'Lato' }, defaultColors: { primary: '#0097e6', secondary: '#00a8ff', accent: '#e1f5fe' } },
  { id: 'innovant', name: 'Innovant', description: 'Design moderne avec une barre latérale colorée.', preview: '/previews/innovant.svg', category: 'créatif', layout: 'two-column', fonts: { heading: 'Nunito', body: 'Nunito' }, defaultColors: { primary: '#130f40', secondary: '#f9ca24', accent: '#7ed6df' } },
  { id: 'traditionnel', name: 'Traditionnel', description: 'Le format classique qui fait ses preuves depuis des années.', preview: '/previews/traditionnel.svg', category: 'classique', layout: 'single-column', fonts: { heading: 'Times New Roman', body: 'Times New Roman' }, defaultColors: { primary: '#000000', secondary: '#444444', accent: '#f0f0f0' } },
  { id: 'express', name: 'Express', description: "Simple et rapide, concentré sur l'essentiel.", preview: '/previews/express.svg', category: 'minimaliste', layout: 'single-column', fonts: { heading: 'Helvetica', body: 'Helvetica' }, defaultColors: { primary: '#353b48', secondary: '#7f8fa6', accent: '#dcdde1' } },
  { id: 'master-degree', name: 'Master / Étudiant', description: 'Idéal pour les étudiants et jeunes diplômés.', preview: '/previews/master-degree.svg', category: 'moderne', layout: 'two-column', fonts: { heading: 'Quicksand', body: 'Inter' }, defaultColors: { primary: '#574b90', secondary: '#786fa6', accent: '#f3e6ff' } },
  { id: 'stage', name: 'Stage / Alternance', description: 'Parfait pour les candidatures en stage ou alternance.', preview: '/previews/stage.svg', category: 'moderne', layout: 'single-column', fonts: { heading: 'Poppins', body: 'Inter' }, defaultColors: { primary: '#e77f67', secondary: '#f19066', accent: '#faf0e6' } },
  { id: 'detail', name: 'Détaillé', description: 'CV complet avec sections détaillées pour profils expérimentés.', preview: '/previews/detail.svg', category: 'classique', layout: 'single-column', fonts: { heading: 'Crimson Text', body: 'Source Sans Pro' }, defaultColors: { primary: '#3d3d3d', secondary: '#595959', accent: '#f5f0e1' } },
  { id: 'graphique', name: 'Graphique', description: 'CV visuel avec barres de progression et éléments graphiques.', preview: '/previews/graphique.svg', category: 'créatif', layout: 'two-column', fonts: { heading: 'Bebas Neue', body: 'Open Sans' }, defaultColors: { primary: '#30336b', secondary: '#be2edd', accent: '#f0f0ff' } },
  { id: 'photo-ready', name: 'Avec Photo', description: 'Template avec espace photo bien intégré.', preview: '/previews/photo-ready.svg', category: 'classique', layout: 'single-column', fonts: { heading: 'Work Sans', body: 'Work Sans' }, defaultColors: { primary: '#2f3640', secondary: '#487eb0', accent: '#f5f6fa' } },
  { id: 'magasinier', name: 'Logistique / Magasinier', description: 'Pour les métiers de la logistique, magasinage et entrepôt.', preview: '/previews/magasinier.svg', category: 'classique', layout: 'single-column', fonts: { heading: 'Roboto', body: 'Roboto' }, defaultColors: { primary: '#e1b12c', secondary: '#4cd137', accent: '#f5f6fa' } },
  { id: 'femme', name: 'Élégance', description: 'Design raffiné aux couleurs douces.', preview: '/previews/femme.svg', category: 'créatif', layout: 'two-column', fonts: { heading: 'Playfair Display', body: 'Lato' }, defaultColors: { primary: '#b71540', secondary: '#e77f67', accent: '#fce4ec' } },
]

const data = { templates: {} }
for (const t of templates) {
  data.templates[t.id] = { ...t, id: t.id }
}

fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2), 'utf-8')
console.log(`✅ Base initialisée avec ${templates.length} templates`)
